# Streamlit app

FROM python:3.10.12

RUN apt-get update && apt-get install -y build-essential cmake pkg-config libjpeg-dev libwebp-dev libpng-dev libtiff-dev libopenjp2-7-dev libglib2.0-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libxvidcore-dev libx264-dev \
    libgtk-3-dev libatlas-base-dev gfortran

RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.8.0.zip
RUN unzip opencv.zip
RUN mv opencv-4.8.0 opencv

WORKDIR /opencv
RUN mkdir build
WORKDIR /opencv/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_EXAMPLES=OFF ..
RUN make -j$(nproc)
RUN make install

# Установка конкретных версий библиотек
RUN pip install pip==23.1.2
RUN pip install streamlit==1.33.0
RUN pip install Pillow==9.4.0
RUN pip install ultralytics==8.2.2


# Добавление модели
COPY best.pt /app/

# Добавление изображений в одну директорию с app.py
COPY confusion_matrix_normalized.png /app/
COPY PR_curve.png /app/

# Добавление кода приложения
COPY app.py /app/

# Установка переменных окружения
ENV PORT=8501

# Создание рабочей директории
WORKDIR /app

# Запуск приложения
CMD ["streamlit", "run", "app.py"]

# Дополнительные команды (оставьте только те, которые нужны)
RUN apt-get update && apt-get install -y mesa-common-dev
RUN apt-get update && apt-get upgrade -y
